### ISSUE TITLE
Support Twisty Timer for sub-x calculation

### ISSUE THREAD

**Issue by Kebabrulle4869** [spencerchubb/cubingapp#5]
Could you support files exported from Twisty Timer for the Sub-X calculator? You're free to contact me for a sample file if needed.

**Comment by spencerchubb** [comment]
Yes would you mind sharing a sample file with me? I'm not familiar with twisty timer, is it a mobile app?

If there's a way to share here on github feel free to do so. Also my google drive is the same has my github name

**Comment by Kebabrulle4869** [comment]
[Solves_333_Weilong WRM_2024-04-15_10-13.txt](https://github.com/spencerchubb/cubingapp/files/14981615/Solves_333_Weilong.WRM_2024-04-15_10-13.txt)
Here!

**Comment by spencerchubb** [comment]
done! the feedback is appreciated, definitely let me know about other bugs and ideas

**Comment by Kebabrulle4869** [comment]
The website still says "we don't recognize the file".

**Comment by spencerchubb** [comment]
If you haven't already, maybe try doing a hard refresh in the browser. Ctrl+Shift+R on windows and Cmd+Shift+R on mac

I used your exact file you provided there and it works for me 😥
