### ISSUE TITLE
Wrong Sub-X time

### ISSUE THREAD

**Issue by afonsofrancof** [spencerchubb/cubingapp#6]
When trying to check my Sub-X time, it tells me it's 95% sure I am bellow 1.48 average.
This is for 3x3, so I think maybe the number is ten times smaller than what it should be since my average is around 15.
I am using cstimer csv export.
[csTimerExport_20240503_134711.csv](https://github.com/spencerchubb/cubingapp/files/15202999/csTimerExport_20240503_134711.csv)

**Comment by spencerchubb** [comment]
thank you for letting me know. i've been busy with my last semester of school, but i finally got around to it :)

it was off by a factor of 10, and it should be correct now. if it still shows incorrect result, you may have to hard refresh with Ctrl+Shift+R for windows or Cmd+Shift+R for mac
